### ISSUE TITLE
TODOS to improve xrock_gui

### ISSUE THREAD

**Issue by Priyanka328** [dfki-ric/xrock_gui_model#6]
### TODO

- [x] run gui  serverless 
- [x] add toolbar for xrock_tool 
   - [x] add icons for add , load , save,  reload
   - [x]  add a combobox for backend selection
   - [x] add text field for the db address  and URL edit
- [x] handle all exceptions in qmessgebox to make it user friendly
- [x] save history on every node deletion
- [x]  add one more button to add component in model_widget 
- [x] update tab captions if the name of the corresponding component model has been edited ( at the moment there is only a reload button which basically closes the old tab and loads the previously edited model in another tab)
- [x] implement undo/redo based on history with ctrl + z and ctrl +y
- [x] give title to the dialog
- [x] add icon to xrock_gui
- [x] make allowed domains dropdown
- [x] add tf_enhance as a menu item like export 
- [x]  a pop up dialog if user forget to save
- [x] implement multidb
- [ ] import cnd
- [x]  handle warnings in bagel GUI and osg_graph_viz
